# podman system prune -a -f && podman build -t mycentos .
FROM centos:7
RUN dbus-uuidgen > /etc/machine-id && dbus-uuidgen > /var/lib/dbus/machine-id && \
    sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
RUN yum update -y && yum install -y gtk3 gvim mlocate && updatedb && yum clean all
# CMD [ "sleep", "infinity" ]

